var annotated_dup =
[
    [ "BaseDataStructure", "class_base_data_structure.html", "class_base_data_structure" ],
    [ "bVectorBase", "classb_vector_base.html", "classb_vector_base" ],
    [ "bVectorOrb", "classb_vector_orb.html", "classb_vector_orb" ],
    [ "edge", "classedge.html", "classedge" ],
    [ "HessianBase", "class_hessian_base.html", "class_hessian_base" ],
    [ "HessianOrb", "class_hessian_orb.html", "class_hessian_orb" ],
    [ "HuberKernel", "class_huber_kernel.html", "class_huber_kernel" ],
    [ "InformationMatrixBase", "class_information_matrix_base.html", "class_information_matrix_base" ],
    [ "InformationMatrixCompressed", "class_information_matrix_compressed.html", "class_information_matrix_compressed" ],
    [ "InformationMatrixOrb", "class_information_matrix_orb.html", "class_information_matrix_orb" ],
    [ "JacobianBase", "class_jacobian_base.html", "class_jacobian_base" ],
    [ "JacobianCompressed", "class_jacobian_compressed.html", "class_jacobian_compressed" ],
    [ "OptimizationAlgorithmBase", "class_optimization_algorithm_base.html", "class_optimization_algorithm_base" ],
    [ "OptimizationAlgorithmGN", "class_optimization_algorithm_g_n.html", null ],
    [ "OptimizationAlgorithmLevenberg", "class_optimization_algorithm_levenberg.html", "class_optimization_algorithm_levenberg" ],
    [ "OptimizerBase", "class_optimizer_base.html", "class_optimizer_base" ],
    [ "OptimizerFactory", "class_optimizer_factory.html", "class_optimizer_factory" ],
    [ "OptimizerFactoryOrbSlamNew", "class_optimizer_factory_orb_slam_new.html", "class_optimizer_factory_orb_slam_new" ],
    [ "OptimizerFactoryProducer", "class_optimizer_factory_producer.html", "class_optimizer_factory_producer" ],
    [ "OptimizerOrbSlam", "class_optimizer_orb_slam.html", "class_optimizer_orb_slam" ],
    [ "OptimizerSettings", "class_optimizer_settings.html", "class_optimizer_settings" ],
    [ "ParameterUpdateBase", "class_parameter_update_base.html", "class_parameter_update_base" ],
    [ "ParameterVectorBase", "class_parameter_vector_base.html", "class_parameter_vector_base" ],
    [ "parameterVectorMarginalized", "classparameter_vector_marginalized.html", "classparameter_vector_marginalized" ],
    [ "ProblemStructure", "class_problem_structure.html", "class_problem_structure" ],
    [ "Propertise", "struct_propertise.html", "struct_propertise" ],
    [ "ReprojectionBase", "class_reprojection_base.html", "class_reprojection_base" ],
    [ "ResidualsBase", "class_residuals_base.html", "class_residuals_base" ],
    [ "ResidualsCompressed", "class_residuals_compressed.html", "class_residuals_compressed" ],
    [ "RobustKernelBase", "class_robust_kernel_base.html", "class_robust_kernel_base" ],
    [ "SolverBase", "class_solver_base.html", "class_solver_base" ],
    [ "SolverMarginalized", "class_solver_marginalized.html", "class_solver_marginalized" ],
    [ "SolverOrb", "class_solver_orb.html", "class_solver_orb" ],
    [ "Timer", "class_timer.html", "class_timer" ],
    [ "Vertex", "class_vertex.html", "class_vertex" ]
];